import dotenv from "dotenv";

dotenv.config();

export const {
  PORT,
  DB_URI,
  JWT_SECRET,
  NODE_ENV,
  BASE_URL,
  JWT_EXPIRES_IN,
  JWT_COOKIE_EXPIRES_IN,
  EMAIL_USERNAME,
  EMAIL_PASSWORD,
  EMAIL_USE_TEST_SERVICE,
  BREVO_API_KEY,
  BREVO_SENDER_EMAIL,
  BREVO_SENDER_NAME,
  STREAM_API_KEY,
  STREAM_API_SECRET,
} = process.env;
