import { Router } from "express";
import { createCompany } from "../controllers/createCompany/create-company.controller.js";
import { findCompany } from "../controllers/findCompany/find-company.controller.js";
import { updateCompany } from "../controllers/updateCompany/update-company.controller.js";
import { deleteCompany } from "../controllers/deleteCompany/delete-company.controller.js";
import { findCompanyMembers } from "../controllers/findCompanyMembers/find-company-members.controller.js";
import { findCurrentCompany } from "../controllers/findCurrentCompany/find-current-company.controller.js";
import { authorize } from "../../../shared/infrastructure/middlewares/auth.middlewares.js";
import { findRecentMembers } from "../controllers/findRecentMembers/find-recent-members.controller.js";
import { updateCompanySettings } from "../controllers/updateSettings/update-company-settings.controller.js";
import { deactivateCompany } from "../controllers/deactivateCompany/deactivate-company.controller.js";
import { findInvitationByCompany } from "../../../invitation/presentation/controllers/findByCompanyId/find-by-company.controller.js";
import { promoteCompanyMember } from "../controllers/promoteMember/promote-member.controller.js";
import { removeCompanyMember } from "../controllers/removeMember/remove-company-member.controller.js";
const companyRoute = Router();
companyRoute.post("/", authorize, createCompany);
companyRoute.get("/:id", findCompany);
companyRoute.get("/:id/current", authorize, findCurrentCompany);
companyRoute.get("/:id/members", authorize, findCompanyMembers);
companyRoute.get("/:id/invitations", authorize, findInvitationByCompany);
companyRoute.get("/:id/recent-members", authorize, findRecentMembers);
companyRoute.patch("/:id/settings", authorize, updateCompanySettings);
companyRoute.patch("/:id/deactivate", authorize, deactivateCompany);
companyRoute.patch("/:id/members/:memberId/promote", authorize, promoteCompanyMember);
companyRoute.delete("/:id/members/:memberId", authorize, removeCompanyMember);
companyRoute.put("/:id", authorize, updateCompany);
companyRoute.delete("/:id", authorize, deleteCompany);
export default companyRoute;
